### ISSUE TITLE
Please help, I can't make example work

### ISSUE THREAD

**Issue by mclxly** [vvo/gifify#103]
I clone the entire codebase to my computer. Run 'node example/index.js' after 'npm i':
```
events.js:188
      throw err;
      ^

Error: Unhandled "error" event. (gifsicle:<stdin>: empty file
)
    at Socket.emit (events.js:186:19)
    at Socket.gotSomeErrors (/data/gifify/index.js:53:23)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

```

**Comment by vvo** [comment]
Just tried and it worked, maybe check you have the right dependencies?

> gifified /Users/vvo/Dev/gifify/example/movie.mp4 to /Users/vvo/Dev/gifify/example/movie.gif

Also maybe checkout https://github.com/sindresorhus/gifski-app which is the latest cool kid on the block

**Comment by mclxly** [comment]
@vvo Thank you! Command line it works but programmatic doesn't.

Btw, I'm going to build a web service to convert mp4 to gif.
