### ISSUE TITLE
error with moment on fresh installation

### ISSUE THREAD

**Issue by mrkrstphr** [vvo/gifify#25]
Fresh install:

    npm install -g gifify

Results in:

```text
$ gifify vidz.mov -o delete-invitations.gif

/usr/local/lib/node_modules/gifify/node_modules/moment-duration-format/lib/moment-duration-format.js:202
	moment.duration.fn.format = function () {
	                          ^
TypeError: Cannot set property 'format' of undefined
    at /usr/local/lib/node_modules/gifify/node_modules/moment-duration-format/lib/moment-duration-format.js:202:28
    at Object.<anonymous> (/usr/local/lib/node_modules/gifify/node_modules/moment-duration-format/lib/moment-duration-format.js:482:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gifify/index.js:4:1)
    at Module._compile (module.js:456:26)
```

**Comment by vvo** [comment]
fixed @mrkrstphr, try

```sh
npm install -g gifify@2.1.2
```
