### ISSUE TITLE
gifsicle: unrecognized option ‘--lossy=80’

### ISSUE THREAD

**Issue by kilianc** [vvo/gifify#49]
```js
  const get = require('request').get
  const readStream = get(someURL)
  const gif = require('fs').createWriteStream(`${this.params.id}.gif`)
  gifify(readStream, {}).pipe(gif)
```

throws

```
events.js:159
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (gifsicle: unrecognized option ‘--lossy=80’
Usage: gifsicle [OPTION | FILE | FRAME]...
Try 'gifsicle --help' for more information.
)
    at Socket.emit (events.js:157:17)
    at Socket.gotSomeErrors (/.../node_modules/gifify/index.js:53:23)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:534:20)
```

**Comment by kilianc** [comment]
my bad, I had wrong binary in my PATH
