### ISSUE TITLE
convert: no images defined `gif:-' @ error/convert.c/ConvertImageCommand/3257

### ISSUE THREAD

**Issue by kilianc** [vvo/gifify#50]
```js
const get = require('request').get
const readStream = get(someURL)
const gif = require('fs').createWriteStream(`${this.params.id}.gif`)
gifify(readStream, {}).pipe(gif)
````

yields

```
Error: Uncaught, unspecified "error" event. (convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
convert: no images defined `gif:-' @ error/convert.c/ConvertImageCommand/3257.
)
    at Socket.emit (events.js:157:17)
    at Socket.gotSomeErrors (/.../node_modules/gifify/index.js:53:23)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:534:20)
```

**Comment by vvo** [comment]
I have no idea, it might be because the video you are using is not https://gpac.wp.mines-telecom.fr/mp4box/ but I am really not sure, create a reproduction repo

**Comment by vvo** [comment]
also see https://github.com/vvo/gifify/search?utf8=%E2%9C%93&q=no+decode+delegate&type=Issues

**Comment by jblamber** [comment]
In my case, this was because I was trying to convert a portion of a video that didnt exist - say seconds 30-34 of a 7 second mp4.
