### ISSUE TITLE
Passing in a Readable stream to gifify does not work in node

### ISSUE THREAD

**Issue by lobabob** [vvo/gifify#93]
If I do
```javascript
outputFileStream = fs.createWriteStream('out.gif');
gifify('blah.gif', { ... }).pipe(outputFileStream);
```
it works, but if I do
```javascript
inputFileStream = fs.createReadStream('blah.gif');
outputFileStream = fs.createWriteStream('out.gif');
gifify(inputFileStream, { ... }).pipe(outputFileStream);
```
it fails with the following
```
Error: Uncaught, unspecified "error" event. (convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
convert: no images defined `gif:-' @ error/convert.c/ConvertImageCommand/3210.
)
    at Socket.emit (events.js:163:17)
    at Socket.gotSomeErrors (/home/farhan/projects/ReverseGifRedditBot/node_modules/gifify/index.js:53:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

**Comment by vvo** [comment]
Have a look at the other issues: https://github.com/vvo/gifify/search?q=no+decode+delegate+for+this+image&type=Issues&utf8=%E2%9C%93
