### ISSUE TITLE
Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by UNST4BL3** [vvo/gifify#94]
OS: Debian 8 x64
Node: v8.1.0
NPM: v5.0.3

**Receiving this error:**
```
RangeError: Maximum call stack size exceeded
    at emitOne (events.js:113:17)
    at ChildProcess.emit (events.js:210:7)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
```

**With this code:**
```
const express = require('express');
const ydl = require('youtube-dl');
const gifify = require('gifify');
const fs = require('fs');

const app = express();
app.listen(80);

const video = ydl('https://www.youtube.com/watch?v=o-qK3u97iB0');

app.get('/', (req, res) => {
	gifify(video, { fps: 29.97 }).pipe(res);
});
```

**Comment by Beanow** [comment]
Same issue v2.4.0 gifify with giflossy.
Ubuntu 16.04 based, node v6.9.4, npm 3.10.10

**Comment by Beanow** [comment]
I think the error is due to:
https://github.com/vvo/gifify/blob/master/index.js#L49

```javascript
  [ffmpeg, convert, gifsicle].forEach(function handleErrors(child) {
    child.on('error', gifsicle.emit.bind(gifsicle, 'error'));
    child.stderr.on('data', function gotSomeErrors(buf) {
      // emit errors on the resolved stream
      gifsicle.stdout.emit('error', buf.toString());
    });
  });
```

The `gifsicle` error event, would emit another `gifsicle` error.

**Comment by vvo** [comment]
Any of you can try to fix this? I am not yet using node v8.

**Comment by Beanow** [comment]
It's not v8 specific. Whenever the gifsicle object emits an error, you get an infinite loop of emitting more errors. You need to handle gifsicle's error events differently and it will fix this issue. What the error was that gifsicle emitted is a different issue.

**Comment by vvo** [comment]
Taking PRs to solve this.

**Comment by Beanow** [comment]
I'll pass since I haven't looked into it enough to see how you *want* error handling to work. I just butchered it to find my underlying problem was #95.

**Comment by samuelpmish** [comment]
I'm hitting this as well, first try after installing `gifify` and I'm met with 
```
sam@provolone:~$ gifify myvideo.mp4 -o video.gif
Generating GIF, please wait...
node:events:460
EventEmitter.prototype.emit = function emit(type, ...args) {
                                           ^

RangeError: Maximum call stack size exceeded
    at ChildProcess.emit (node:events:460:44)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:events:513:28)
```
